SERP_API_KEY: "0c7b1581adbbd6d6ef87658d9dfc0936655dd13087442a0c23decb6c32645571"
OPENAI_API_KEY: "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"
ENGINE: "yelp_reviews"
PLACE_ID: "cFTq5MmBDPb_VEqQXPw2Dw"
REVIEWS_PATH: "./data/reviews/"
EMBEDDINGS_PATH: "./data/embeddings/"